ui:
  ssl: false
  host: dspace-frontend
  port: 4000
  nameSpace: /
  rateLimiter:
    windowMS: 60000
    max: 500
  useProxies: true

rest:
  ssl: true
  host: repositorio.fcyt.uader.edu.ar
  port: 443
  nameSpace: /server
