FROM node:16.18.1

# Instalar herramientas necesarias
RUN apt-get update && apt-get install -y wget git

# Verificar la versión de yarn e instalar PM2
RUN yarn --version && \
    npm install --global pm2

# Crear directorio de trabajo
WORKDIR /dspace-angular

# Descargar DSpace Angular
RUN wget https://github.com/DSpace/dspace-angular/archive/refs/tags/dspace-7.6.tar.gz
RUN tar zxvf dspace-7.6.tar.gz
RUN mv dspace-angular-dspace-7.6/* .
# RUN rm -rf dspace-angular-dspace-7.6 dspace-7.6.tar.gz

# Instalar dependencias
RUN yarn install

# Copiar archivos de configuración
COPY config.prod.yml config/config.prod.yml

# Copiar archivos de personalizacion 
#Configuracion del tema
COPY fcyt src/themes

# Copiar archivos de configuracion del tema
COPY aeager-themes.module.ts src/themes/eager-themes.module.ts

# Copiar archivos de configuracion de angular
COPY angular.json .

# Construir la aplicación
RUN yarn build:prod

EXPOSE 4000

# Comando para iniciar la aplicación
CMD ["yarn", "serve:ssr"]
