version: '3'
services:
  db:
    image: postgres:14
    container_name: dspace-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: dspace
      POSTGRES_USER: dspace
      POSTGRES_PASSWORD: dspace
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./create_pgcrypto.sql:/docker-entrypoint-initdb.d/create_pgcrypto.sql
    networks:
      - dspace-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: dspace-frontend
    ports:
      - 4000:4000
    depends_on:
      - backend
    networks:
      - dspace-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: dspace-backend
    ports:
      - 8080:8080
    command:
      ["bash","/start.sh"]
    depends_on:
      - db
    networks:
      - dspace-network

networks:
  dspace-network:
    driver: bridge
