# Usamos Ubuntu 22.04 como base
FROM ubuntu:22.04

# Establecemos variables de entorno para que no haya interacción durante la instalación
ENV DEBIAN_FRONTEND=noninteractive

# Actualizamos el sistema y agregamos el repositorio oficial de PostgreSQL
RUN apt-get update && apt-get install -y wget gnupg2 lsb-release \
    && echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" | tee /etc/apt/sources.list.d/pgdg.list \
    && wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - \
    && apt-get update \
    && apt-get install -y postgresql-14 postgresql-contrib-14 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Creamos un directorio para la base de datos
RUN mkdir -p /var/lib/postgresql/data

# Cambiamos el propietario del directorio a postgres y establecemos permisos adecuados
RUN chown -R postgres:postgres /var/lib/postgresql/data
RUN chmod -R 700 /var/lib/postgresql/data

# Exponemos el puerto 5432 para conexiones externas
EXPOSE 5432

# Argumentos para la configuración de la base de datos
ARG POSTGRES_DB=dspace
ARG POSTGRES_USER=dspace
ARG POSTGRES_PASSWORD=dspace

# Configurar variables de entorno para la base de datos
ENV POSTGRES_DB=${POSTGRES_DB}
ENV POSTGRES_USER=${POSTGRES_USER}
ENV POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# Cambiamos al usuario postgres para inicializar el servicio
USER postgres

# Inicializamos la base de datos
RUN /usr/lib/postgresql/14/bin/initdb -D /var/lib/postgresql/data

# Comando para eliminar PID y luego iniciar PostgreSQL
CMD ["bash", "-c", "rm -f /var/lib/postgresql/data/postmaster.pid && exec /usr/lib/postgresql/14/bin/postgres -D /var/lib/postgresql/data"]